### ISSUE TITLE
Problems occurred during installation

### ISSUE THREAD

**Issue by KuriKenOld** [YoheiKakiuchi/robotsimulation-docker#1]
I've had a few problems when building the environment following the instructions written on the README.md so I'd like to ask a few questions. (The OS is Ubuntu 14.04 and there is no NVIDIA running on my PC.)

First of all, when I tried to use the command
`$ docker run hello-world`
the following message appeared.
```
docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.27/containers/create: dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.
```

The same message appeared when using the "./build.sh" command.
This problem was solved by adding "sudo" before the command but is there supposed to be a way to execute this command without using "sudo"?

Another problem occurred after using the the following 2 commands.
`$ sudo nvidia-docker run --rm nvidia/cuda nvidia-smi`
`$ ./run.sh rtmlaunch hrpsys_choreonoid_tutorials jaxon_jvrc_choreonoid.launch`

The error message was
``` 
nvidia-docker | 2017/05/24 14:11:21 Error: Could not load UVM kernel module. Is nvidia-modprobe installed?
```

It seemed that the "nvidia-modprobe" was not installed in my PC, so I tried installing it using the"sudo apt-get update" & the "sudo apt-get install nvidia-modprobe" command, but the same message appeared again after doing so.

How can I solve this problem?

**Comment by nekketsuuu** [comment]
@KenyuKurimoto You can run `docker` without `sudo` if the Docker daemon has the access right to Unix sockets. By default, Docker doesn't have the right due to a secuiry issue. The details are described [here](https://askubuntu.com/questions/477551/how-can-i-use-docker-without-sudo) and [here](https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface).

**Comment by YoheiKakiuchi** [comment]
@KenyuKurimoto
nvidia-docker requires nvidia-modprobe . So, apt-get nvidia-modprobe was needed.

Other problems may be solved by below commands. 
~~~
$ sudo gpasswd -a $USER docker
$ sudo gpasswd -a $USER nvidia-docker
$ sudo reboot
~~~

You can check groups below commands.
~~~
$ groups $USER
$ getent group docker
~~~

**Comment by KuriKenOld** [comment]
@YoheiKakiuchi @nekketsuuu 
Thanks for your reply.

>Other problems may be solved by below commands.
$ sudo gpasswd -a $USER docker
$ sudo gpasswd -a $USER nvidia-docker
$ sudo reboot

Unfortunately, I've already tried adding docker & nvidia-docker and still, the above-mentioned commands don't work without sudo.
```
$ groups $USER
kenyukurimoto : kenyukurimoto adm cdrom sudo dip plugdev lpadmin sambashare docker nvidia-docker
$ docker run hello-world
docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.27/containers/create: dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.
```

> So, apt-get nvidia-modprobe was needed.

Also,  I've already installed nvidia-modprobe via "sudo apt-get install", and this did not solve the problem.
Do you mean that I should install it with a different method?

**Comment by YoheiKakiuchi** [comment]
If you can run docker command with sudo, it is just a problem of permission.
I recommend to reinstall docker after completely unistalling docker.
If it does not work, I have no idea for this problem.
