### ISSUE TITLE
How to reset a robot pose for standing when the robot fails down.

### ISSUE THREAD

**Issue by mukuact** [YoheiKakiuchi/robotsimulation-docker#10]
I'm a beginner of the choreonoid, so maybe a stupid question.

I'd like the robot to walk at a ball and make a pick up motion.
When I send a pose to the real robot, sometimes it fails down because of loss of balance.

Then, to restart where a robot is standing, I have to kill docker process and re-execute 'run.sh'.

How can I reset the robot state at standing pose without rerun choreonoid?

**Comment by YoheiKakiuchi** [comment]
You can use ```(reset-simulation :coords coordinates)```.
The robot is located at coordinates.
https://github.com/start-jsk/rtmros_choreonoid/blob/master/hrpsys_choreonoid_tutorials/euslisp/action_and_perception/walk-to-target-lib.l#L219-L233

If you want to know the coordinates of the robot in the simulation,
you can use ```(get-coords-on-simulation)```
https://github.com/start-jsk/rtmros_choreonoid/blob/master/hrpsys_choreonoid/scripts/choreonoid-service-client.l#L77-L90

If you do not use stabilizer and autobalancer,
you can use ```(reset-position :coords coordinates)```
https://github.com/YoheiKakiuchi/robotsimulation-docker/blob/master/choreonoid_docker/sample-program.l#L17-L20

**Comment by mukuact** [comment]
Thank you for your advice!

Finally I make reset function and I can rerun my-program more faster.
```lisp
(defun reset-all ()
  (send *robot* :reset-pose)
  (send *robot* :fix-leg-to-coords (make-coords))
  (send *ri* :angle-vector (send *robot* :angle-vector) 1000)
  (send *ri* :wait-interpolation)
  (reset-simulation :args (get-coords-on-simulation))
)

```
