### ISSUE TITLE
Insertができない

### ISSUE THREAD

**Issue by dyson8910** [YoheiKakiuchi/robotsimulation-docker#14]
choreonoid上でSR1を動かしているのですが,Insertを押しても姿勢が保持されません.

環境としては
Ubuntu16.04,Thinkpad T450を使用しています.

README.mdにあるように
docker run hello-world
が実行できることは確認しています.
nvidiaが入っていないため,
./run_no_gl_choreonoid.sh
でchoreonoidを立ち上げています.
Insertを押しても姿勢がPoseRollに保持されず,
Updateも押せないままになってしまっています.

**Comment by YoheiKakiuchi** [comment]
@kindsenior さんが詳しい？

左側のWorld,SR1とかのツリーが表示されているところで、
PoseSeqを加える前に、ロボットのモデルを選択しておく必要がある。

こうすると、以下のようにSR1の子供としてPoseSeqができる
~~~
World
  -> SR1
    -> PoseSeq
~~~

Pose Rollのビューを見えるようにしたら、
PoseSeqを選択（ツリーのところでクリックしてハイライトされる）すると、Insertできるようになると思う

**Comment by dyson8910** [comment]
@Naoki-Hiraoka からちょうど今伺いました.
先生の仰るようにロボットのモデルを選択せずにPoseSeqを加えていたことが原因でした.
PoseSeqを加え直したところ,SR1を動かすことができました.
ありがとうございます.
