### ISSUE TITLE
nvidiaがインストールできない

### ISSUE THREAD

**Issue by ayfujii** [YoheiKakiuchi/robotsimulation-docker#8]
nvidiaがうまくインストールできません。

環境としては
ubuntu14.04
ThinkPad T450
を使用しています。
同様の環境でインストールできたという話もあるのですが、私のパソコンでは何度繰り返してもできません。

 $ lspci | grep GeForce　とすると
04:00.0 3D controller: NVIDIA Corporation GM108M [GeForce 940M] (rev a2)
と出力されます。

nvidiaの公式サイトで対応しているドライバを検索すると384.59と出てきたため、
 $ sudo apt-get install nvidia-384
でダウンロードしました。
(ちなみに以前ダウンロードしようとしたときは対応するドライバを検索すると375だったと思うのですが、どちらで施行してもできませんでした。)

その後rebootしてubuntuを選択して立ち上げると画面がブラックアウトしてしまいます。
CUIでログインして
$ nvidia-smi
とすると下記のように出力されます。

![img_9171](https://user-images.githubusercontent.com/26871363/28713227-38b93f26-73c9-11e7-8eef-cef18aa1fdd6.JPG)

どうにもならないのでnvidiaをremoveして再度rebootすると元に戻るということを繰り返しています。
noveauを無効にしたり、X Serverを停止させたり、bumblebeeをインストールしたりしてみたのですが、いずれの方法もうまくいきませんでした。
どうしたらインストールできますでしょうか？

**Comment by sshige** [comment]
以前、T450ではありませんが、他のPCにて自分も似たような症状に遭遇したことがありますので、参考になればと思い、連絡させていただきました。

aptではなくてshファイルをダウンロードし、Xserverを停止させたのち、CUIからshファイルを実行してインストールする場合でも同じ状況になりますか？

自分はaptでは入らずshファイルで入れるようにしておりましたので、もしかしたらこれで解決するかもしれません。

**Comment by sshige** [comment]
[https://developer.nvidia.com/cuda-downloads](https://developer.nvidia.com/cuda-downloads)

shファイルはこのサイトのrunfile(local)のことです。

**Comment by mukuact** [comment]
> nvidiaの公式サイトで対応しているドライバを検索すると384.59と出てきたため、

たまに，これが間違っているっぽいことがあります．
ubuntu14.04 ThinkPad T450
では
`nvidia-375' 
が適するドライバのようです．

**Comment by sshige** [comment]
今気づいたのですが、cudaのインストールと勘違いしていました。

nvidiaのドライバーだけでしたら、nvidiaの[このサイト](http://www.nvidia.co.jp/Download/index.aspx?lang=jp)で対応するrunファイルをダウンロードしてXserverとめて、CUIで実行するのを試してみるといいと思います。

**Comment by ayfujii** [comment]
いろいろとありがとうございます。

様々な方法を試してみたのですが、うまくインストールできず、結局すでにnvidiaがインストールされている共有パソコンを使用させて頂きました。

お騒がせしてしまい、申し訳ありません。
