### ISSUE TITLE
Tf cannot transform from BODY to left_camera_optical_frame.

### ISSUE THREAD

**Issue by mukuact** [YoheiKakiuchi/robotsimulation-docker#9]
Thank you for preparing the simulation environment !
However, in the demo program, I encountered a problem on TF.
I executed these in each terminal, and successfully run every nodes.
```
$ ./run.sh
$ ./exec.sh '/my_entrypoint.sh roslaunch hrpsys_choreonoid_tutorials tracking_recognition.launch gui:=true'
$ ./exec.sh '/my_entrypoint.sh emacs'
```
Then, I put `root@d30368ff2448:/home/choreonoid/catkin_ws/src/rtmros_choreonoid/hrpsys_choreonoid_tutorials/euslisp/action_and_perception# roseus kick-ball-demo.l`  and then (kick-ball-demo) on emacs's shell.

After that, I saw this log and the JAXON robot have never moved.
```
4.irteusgl$ (kick-ball-demo)
;; start walking to the target
[ WARN] [1501655882.311280043, 632.938000000]: waitForTransform failed! : Could not find a connection between 'BODY' and 'left_camera_optical_frame' because they are not part of the same tree.Tf has two or more unconnected trees.. canTransform returned after 8 timeout was 8.
...(same log appears)
...
```

What can I do for fixing this?

**Comment by mukuact** [comment]
Another information here.
The `./exec.sh  /my_entrypoint.sh roseus user_programs/tf-test.l ` publishes the same log as above comment.

**Comment by mukuact** [comment]
rosrun tf view_frames 
[frames.pdf](https://github.com/YoheiKakiuchi/robotsimulation-docker/files/1193052/frames.pdf)

I see there is no connection between some tf tree.

**Comment by YoheiKakiuchi** [comment]
It has been fixed at
https://github.com/start-jsk/rtmros_common/commit/e2ca88ee65dc41c64d4a9cdc25d84bf42c6f41d3

BUT, I forgot update docker_image.
So, I updated yoheikakiuchi/choreonoidsim.

Please try again after ```docker pull yoheikakiuchi/choreonoidsim```

**Comment by mukuact** [comment]
Thank you for rapid reply!!! @YoheiKakiuchi 
The JAXON_red successfully won a goal after updating docker repo.
![screenshot from 2017-08-02 17 16 57](https://user-images.githubusercontent.com/9731882/28864132-7f2d414c-77a6-11e7-94ca-6b8eadadd9d2.png)
